### ISSUE TITLE
PY_MAYA_CALLBACK fails if sys is not imported before executing

### ISSUE THREAD

**Issue by Jawabiscuit** [justinfx/MayaSublime#33] opened 2017-06-05 15:16 UTC
I put an import sys statement in Maya's userSetup.py or .mel and it works.

**Comment by justinfx** [comment] 2017-06-05 21:38
Is this a duplicate of #28? I had fixed this same problem in the past. Can you confirm if you are on an old version? Fixed in 3.0.2

**Comment by justinfx** [comment] 2017-06-06 19:45
Ok, so you manually cloned the plugin instead of using Package Control, which means it won't be auto updating. It will be however old it was when you cloned it. You could type `git log` to see the most recent commit. Or you could look at the "messages" subdirectory and see what the latest version file is. If you run `git pull` do you pick up any new changes.

**Comment by Jawabiscuit** [comment] 2017-06-06 19:57
`git pull`
Already up-to-date.

**Comment by justinfx** [comment] 2017-06-07 02:17
I can't reproduce this problem at work. I will have to try when I have time from another computer. Seems like the problem should have already been fixed but you say you have the latest clone.

**Comment by justinfx** [comment] 2017-06-07 02:19
Hah! I just figure out why I missed it. Needed to enabled the callback :-) I will push up a fix.

**Comment by justinfx** [comment] 2017-06-07 02:29
Pull again and that should fix it. Thanks!

**Closed** 2017-06-07 02:29 UTC

**Comment by Jawabiscuit** [comment] 2017-06-07 14:47
Good on my end :+1:
